var projectList = [
  {
    projectNo: 1,
    projectHighlight: true,
    highlightNo: 1,
    projectName: 'IME FTUI',
    projectType: 'Organization Website',
    projectYear: '2020',
    projectDesc1: 'IME FTUI is an Executive Council of Electrical Engineering Students in Universitas Indonesia. This project goal is to achieve <b>new, fresh, and user-friendly design</b> to provide useful  information for the students of Electrical Engineering.',
    projectDesc2: 'The highlight of this project is to provide a <b>great user experience</b> while maintaining the <b>simplicity</b> of the website.',
    projectMainImg: './assets/ime-ftui/pic1.webp',
    projectDescImg1: './assets/ime-ftui/pic2.webp',
    projectDescImg2: './assets/ime-ftui/pic3.webp',
    projectDocImg1: './assets/ime-ftui/pic4.webp',
    projectDocImg2: './assets/ime-ftui/pic5.webp',
    projectDocImg3: './assets/ime-ftui/pic6.webp',
    projectMobileImg: './assets/ime-ftui/pic7.webp',
    projectSite: 'https://ime.eng.ui.ac.id',
    projectDemo: '',
  },
  {
    projectNo: 2,
    projectHighlight: true,
    highlightNo: 2,
    projectName: 'TIS FTUI',
    projectType: 'Organization Website',
    projectYear: '2021',
    projectDesc1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores doloremque ducimus adipisci accusantium molestias! Ratione sapiente possimus adipisci inventore consequuntur?',
    projectDesc2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores doloremque ducimus adipisci accusantium molestias! Ratione sapiente possimus adipisci inventore consequuntur?',
    projectMainImg: './assets/service-organization.webp',
    projectDescImg1: './assets/service-organization.webp',
    projectDescImg2: './assets/service-organization.webp',
    projectDocImg1: './assets/service-organization.webp',
    projectDocImg2: './assets/service-organization.webp',
    projectDocImg3: './assets/service-organization.webp',
    projectMobileImg: './assets/service-organization.webp',
    projectSite: '',
    projectDemo: '',
  },
]