var projectList = [
  {
    projectNo: 1,
    projectHighlight: true,
    highlightNo: 1,
    projectName: 'IME FTUI',
    projectType: 'Organization Website',
    projectYear: '2020',
    projectDesc1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores doloremque ducimus adipisci accusantium molestias! Ratione sapiente possimus adipisci inventore consequuntur?',
    projectDesc2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores doloremque ducimus adipisci accusantium molestias! Ratione sapiente possimus adipisci inventore consequuntur?',
    projectMainImg: './assets/service-portfolio.png',
    projectDescImg1: './assets/service-portfolio.png',
    projectDescImg2: './assets/sample-cover.png',
    projectDocImg1: './assets/sample-cover.png',
    projectDocImg2: './assets/sample-cover.png',
    projectDocImg3: './assets/sample-cover.png',
    projectMobileImg: './assets/sample-cover.png',
  },
  {
    projectNo: 2,
    projectHighlight: true,
    highlightNo: 2,
    projectName: 'TIS FTUI',
    projectType: 'Organization Website',
    projectYear: '2021',
    projectDesc1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores doloremque ducimus adipisci accusantium molestias! Ratione sapiente possimus adipisci inventore consequuntur?',
    projectDesc2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores doloremque ducimus adipisci accusantium molestias! Ratione sapiente possimus adipisci inventore consequuntur?',
    projectMainImg: './assets/service-organization.png',
    projectDescImg1: './assets/service-organization.png',
    projectDescImg2: './assets/service-organization.png',
    projectDocImg1: './assets/service-organization.png',
    projectDocImg2: './assets/service-organization.png',
    projectDocImg3: './assets/service-organization.png',
    projectMobileImg: './assets/service-organization.png',
  },
]